apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.11.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: echo
  name: echo
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: echo
    spec:
      containers:
      - env:
        - name: SERVICE_NAME
          value: echo
        - name: SERVICE_REGION
          value: ap-southeast-1
        - name: SERVICE_TAGS
          value: traefik.enable=true,traefik.backend=echo,traefik.frontend.entryPoints=http,traefik.frontend.rule=Host:echo.consul.localhost,traefik.frontend.passHostHeader=true
        image: alextanhongpin/echo:0.0.3
        name: echo
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
